/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: akshatmittal (https://sketchfab.com/akshatmittal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-macbook-air-15-space-gray-2023-e8d82e341c794141a2561c2c9d01d79e
Title: Apple Macbook Air 15 (Space Gray) 2023
*/

import * as THREE from 'three'
import { Html, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import InnerApp from './InnerApp'

type GLTFResult = GLTF & {
  nodes: {
    xVreGKoBGSZYMij: THREE.Mesh
    CTBERffHyoCSDBm_0: THREE.Mesh
    hczGzWOWpedUDYd_0: THREE.Mesh
    biHEvGDNnTqamRb: THREE.Mesh
    TyOrApjEOLhYCaF: THREE.Mesh
    vrIckaCELZpnnNK: THREE.Mesh
    SadnAkehSlxIwKv: THREE.Mesh
    OrhpMXCxeprcNok: THREE.Mesh
    aLWGnOLpsFWVSfy: THREE.Mesh
    WDUVUVPpNjdIPkb: THREE.Mesh
    NqUinIWcwSlXpvt: THREE.Mesh
    MaufYfIBnxcfRgH: THREE.Mesh
    aIqeGXayDxWnOWQ: THREE.Mesh
    HrtjMXqDCcINmDE_0: THREE.Mesh
    zWqVyCKpTAuZNiu_0: THREE.Mesh
    MYVKQTLmUkzzlBj_0: THREE.Mesh
    qEJjkxdFZFWJWzR_0: THREE.Mesh
    lvlCIzdfTmsrnsM: THREE.Mesh
    eeWSraIVipLsSmX_0: THREE.Mesh
    PgbYkhvRdcmMeGL: THREE.Mesh
    rktWdhtZkCSmqne: THREE.Mesh
    hztTkkTJBJTZDmk: THREE.Mesh
    bHBjPHbrqJmhyoR: THREE.Mesh
    HHcJitDCPTdgnFk: THREE.Mesh
    DRGkWmkJlgmNDJU: THREE.Mesh
    KMwpdMtieDqmHVU: THREE.Mesh
    KgPDMIRPrxAynTV: THREE.Mesh
    XwGJfoaIrduFPcU: THREE.Mesh
    ACMWKGtOCqXifQY: THREE.Mesh
    BkHyotPbPWzwAAj: THREE.Mesh
    bkcxDtALZjuqGGQ: THREE.Mesh
    ebZHPVwKTmqvgbU: THREE.Mesh
    uSnVzUkbvcGaVtm: THREE.Mesh
    znOBoeqnOAcWvld: THREE.Mesh
    tIZmzvOOHrlOFci: THREE.Mesh
    UmfOhraHkqkMHJr: THREE.Mesh
    roXkINNmErodbSy: THREE.Mesh
    wWWhLQmmNVhThGV: THREE.Mesh
    JoRHkRchuIHZFdI: THREE.Mesh
    qJLFXXZhlqhKvcM: THREE.Mesh
    thJvyyEdPZIkQGr: THREE.Mesh
    juMIjHdkYweLlGP: THREE.Mesh
    zNYAavJLMZZchIX: THREE.Mesh
    bzbXKgxvWZbXAqu: THREE.Mesh
    guzkNjLPdYYIFbm: THREE.Mesh
    CkZgGMshUOhytMM: THREE.Mesh
    oiLbjgjnUUhPosp: THREE.Mesh
    nDWhlgWONddUcnN: THREE.Mesh
    VAcTKRVsYcEMWxB: THREE.Mesh
  }
  materials: {
    dKLyhhkbEyMrqky: THREE.MeshStandardMaterial
    YjmXmicdBWsFQyD: THREE.MeshStandardMaterial
    pEUnNAGXCoAFoUk: THREE.MeshStandardMaterial
    dFfswgailNMtaYj: THREE.MeshStandardMaterial
    AZirwHJdxxcChtp: THREE.MeshStandardMaterial
    dkOmcmuFedorUKC: THREE.MeshStandardMaterial
    VNZklasZKSWjWUk: THREE.MeshStandardMaterial
    OfvrpEsWzbOpbcs: THREE.MeshStandardMaterial
    iFCKstMLETFqCmZ: THREE.MeshStandardMaterial
    ZPlxrBOYjSNYvVB: THREE.MeshStandardMaterial
    rvYnnyqXrbFJXxh: THREE.MeshStandardMaterial
    SsSIPrCyVNTOxvd: THREE.MeshStandardMaterial
    EKOOVJzobzfBYEj: THREE.MeshStandardMaterial
    BfIgIOaUEgyoEft: THREE.MeshStandardMaterial
    zFJMMvikHFjtmzd: THREE.MeshStandardMaterial
    jIhmcgKbjDOICsY: THREE.MeshStandardMaterial
    JKvAHnqjqlqshmY: THREE.MeshStandardMaterial
    wOIDWopwzKBeTNU: THREE.MeshStandardMaterial
    ZrrjpMZNDbttBCc: THREE.MeshStandardMaterial
    RMDHOHZakhhXXHT: THREE.MeshStandardMaterial
    hZBlDyddxAQhuPm: THREE.MeshStandardMaterial
    sRPrqogRtliLLae: THREE.MeshStandardMaterial
    kDpbvvjwMgCSCmF: THREE.MeshStandardMaterial
    AqVxlXuHIFahLKs: THREE.MeshStandardMaterial
    oKQWdLrXUCbYByI: THREE.MeshStandardMaterial
    OFvWomWIIUgmKKA: THREE.MeshStandardMaterial
    mEMAJQfiigHeUXV: THREE.MeshStandardMaterial
    NzmRSNqyvNKhkmK: THREE.MeshStandardMaterial
    ASadxrcBIAXFnLn: THREE.MeshStandardMaterial
    oINmXIPcNKkHSJV: THREE.MeshStandardMaterial
    AvocVUvikCzzMtu: THREE.MeshStandardMaterial
    tyKqaDjBmuwfmrZ: THREE.MeshStandardMaterial
  }
}

export function LaptopModel({ selected, setSelected, setHoverHTML, selectedApp }: {
  selected: boolean,
  setSelected: (value: boolean) => void,
  setHoverHTML: (value: boolean) => void
  selectedApp?: string
}) {
  const { nodes, materials } = useGLTF('/laptop.glb') as GLTFResult

  return (
    <>
      <group dispose={null}>
        <group name="USDRoot" scale={0.01}>
          <group>
            <mesh
              name="xVreGKoBGSZYMij"
              castShadow
              geometry={nodes.xVreGKoBGSZYMij.geometry}
              material={materials.dKLyhhkbEyMrqky}
            />
            <mesh
              name="CTBERffHyoCSDBm_0"
              castShadow
              geometry={nodes.CTBERffHyoCSDBm_0.geometry}
              material={materials.YjmXmicdBWsFQyD}
            />
            <mesh
              name="hczGzWOWpedUDYd_0"
              castShadow
              geometry={nodes.hczGzWOWpedUDYd_0.geometry}
              material={materials.pEUnNAGXCoAFoUk}
            />
            <mesh
              name="biHEvGDNnTqamRb"
              castShadow
              geometry={nodes.biHEvGDNnTqamRb.geometry}
              material={materials.dFfswgailNMtaYj}
            />
            <mesh
              name="TyOrApjEOLhYCaF"
              castShadow
              geometry={nodes.TyOrApjEOLhYCaF.geometry}
              material={materials.AZirwHJdxxcChtp}
            />
            <mesh
              name="vrIckaCELZpnnNK"
              castShadow
              geometry={nodes.vrIckaCELZpnnNK.geometry}
              material={materials.dkOmcmuFedorUKC}
            />
          </group>
          <mesh
            name="SadnAkehSlxIwKv"
            castShadow
            geometry={nodes.SadnAkehSlxIwKv.geometry}
            material={new THREE.MeshBasicMaterial({ color: 'black' })}>
            <Html className="content" rotation-x={-Math.PI / 9} position={[-12.2, 18.5, -18.87]} transform occlude>
              <div className="wrapper"
                onPointerEnter={(e) => (e.stopPropagation(), setHoverHTML(true))}
                onPointerLeave={(e) => (e.stopPropagation(), setHoverHTML(false))}
                onClick={(e) => (e.stopPropagation(), setSelected(true))}>
                  <InnerApp selectedApp={selectedApp} selected={selected} />
              </div>
            </Html>
          </mesh>
          <group>
            <mesh
              name="OrhpMXCxeprcNok"
              castShadow
              geometry={nodes.OrhpMXCxeprcNok.geometry}
              material={materials.OfvrpEsWzbOpbcs}
            />
            <mesh
              name="aLWGnOLpsFWVSfy"
              castShadow
              geometry={nodes.aLWGnOLpsFWVSfy.geometry}
              material={materials.iFCKstMLETFqCmZ}
            />
            <mesh
              name="WDUVUVPpNjdIPkb"
              castShadow
              geometry={nodes.WDUVUVPpNjdIPkb.geometry}
              material={materials.ZPlxrBOYjSNYvVB}
            />
            <mesh
              name="NqUinIWcwSlXpvt"
              castShadow
              geometry={nodes.NqUinIWcwSlXpvt.geometry}
              material={materials.rvYnnyqXrbFJXxh}
            />
            <mesh
              name="MaufYfIBnxcfRgH"
              castShadow
              geometry={nodes.MaufYfIBnxcfRgH.geometry}
              material={materials.SsSIPrCyVNTOxvd}
            />
            <mesh
              name="aIqeGXayDxWnOWQ"
              castShadow
              geometry={nodes.aIqeGXayDxWnOWQ.geometry}
              material={materials.EKOOVJzobzfBYEj}
            />
            <mesh
              name="HrtjMXqDCcINmDE_0"
              castShadow
              geometry={nodes.HrtjMXqDCcINmDE_0.geometry}
              material={materials.BfIgIOaUEgyoEft}
            />
            <mesh
              name="zWqVyCKpTAuZNiu_0"
              castShadow
              geometry={nodes.zWqVyCKpTAuZNiu_0.geometry}
              material={materials.zFJMMvikHFjtmzd}
            />
            <mesh
              name="MYVKQTLmUkzzlBj_0"
              castShadow
              geometry={nodes.MYVKQTLmUkzzlBj_0.geometry}
              material={materials.jIhmcgKbjDOICsY}
            />
            <mesh
              name="qEJjkxdFZFWJWzR_0"
              castShadow
              geometry={nodes.qEJjkxdFZFWJWzR_0.geometry}
              material={materials.JKvAHnqjqlqshmY}
            />
            <mesh
              name="lvlCIzdfTmsrnsM"
              castShadow
              geometry={nodes.lvlCIzdfTmsrnsM.geometry}
              material={materials.iFCKstMLETFqCmZ}
            />
            <mesh
              name="eeWSraIVipLsSmX_0"
              castShadow
              geometry={nodes.eeWSraIVipLsSmX_0.geometry}
              material={materials.JKvAHnqjqlqshmY}
            />
            <mesh
              name="PgbYkhvRdcmMeGL"
              castShadow
              geometry={nodes.PgbYkhvRdcmMeGL.geometry}
              material={materials.wOIDWopwzKBeTNU}
            />
            <mesh
              name="rktWdhtZkCSmqne"
              castShadow
              geometry={nodes.rktWdhtZkCSmqne.geometry}
              material={materials.ZrrjpMZNDbttBCc}
            />
            <mesh
              name="hztTkkTJBJTZDmk"
              castShadow
              geometry={nodes.hztTkkTJBJTZDmk.geometry}
              material={materials.ZrrjpMZNDbttBCc}
            />
            <mesh
              name="bHBjPHbrqJmhyoR"
              castShadow
              geometry={nodes.bHBjPHbrqJmhyoR.geometry}
              material={materials.ZrrjpMZNDbttBCc}
            />
            <mesh
              name="HHcJitDCPTdgnFk"
              castShadow
              geometry={nodes.HHcJitDCPTdgnFk.geometry}
              material={materials.RMDHOHZakhhXXHT}
            />
            <mesh
              name="DRGkWmkJlgmNDJU"
              castShadow
              geometry={nodes.DRGkWmkJlgmNDJU.geometry}
              material={materials.RMDHOHZakhhXXHT}
            />
            <mesh
              name="KMwpdMtieDqmHVU"
              castShadow
              geometry={nodes.KMwpdMtieDqmHVU.geometry}
              material={materials.RMDHOHZakhhXXHT}
            />
            <mesh
              name="KgPDMIRPrxAynTV"
              castShadow
              geometry={nodes.KgPDMIRPrxAynTV.geometry}
              material={materials.hZBlDyddxAQhuPm}
            />
            <mesh
              name="XwGJfoaIrduFPcU"
              castShadow
              geometry={nodes.XwGJfoaIrduFPcU.geometry}
              material={materials.YjmXmicdBWsFQyD}
            />
            <mesh
              name="ACMWKGtOCqXifQY"
              castShadow
              geometry={nodes.ACMWKGtOCqXifQY.geometry}
              material={materials.RMDHOHZakhhXXHT}
            />
            <mesh
              name="BkHyotPbPWzwAAj"
              castShadow
              geometry={nodes.BkHyotPbPWzwAAj.geometry}
              material={materials.sRPrqogRtliLLae}
            />
            <mesh
              name="bkcxDtALZjuqGGQ"
              castShadow
              geometry={nodes.bkcxDtALZjuqGGQ.geometry}
              material={materials.RMDHOHZakhhXXHT}
            />
            <mesh
              name="ebZHPVwKTmqvgbU"
              castShadow
              geometry={nodes.ebZHPVwKTmqvgbU.geometry}
              material={materials.kDpbvvjwMgCSCmF}
            />
            <mesh
              name="uSnVzUkbvcGaVtm"
              castShadow
              geometry={nodes.uSnVzUkbvcGaVtm.geometry}
              material={materials.AqVxlXuHIFahLKs}
            />
            <mesh
              name="znOBoeqnOAcWvld"
              castShadow
              geometry={nodes.znOBoeqnOAcWvld.geometry}
              material={materials.dKLyhhkbEyMrqky}
            />
            <mesh
              name="tIZmzvOOHrlOFci"
              castShadow
              geometry={nodes.tIZmzvOOHrlOFci.geometry}
              material={materials.oKQWdLrXUCbYByI}
            />
            <mesh
              name="UmfOhraHkqkMHJr"
              castShadow
              geometry={nodes.UmfOhraHkqkMHJr.geometry}
              material={materials.OFvWomWIIUgmKKA}
            />
            <mesh
              name="roXkINNmErodbSy"
              castShadow
              geometry={nodes.roXkINNmErodbSy.geometry}
              material={materials.oKQWdLrXUCbYByI}
            />
            <mesh
              name="wWWhLQmmNVhThGV"
              castShadow
              geometry={nodes.wWWhLQmmNVhThGV.geometry}
              material={materials.OFvWomWIIUgmKKA}
            />
            <mesh
              name="JoRHkRchuIHZFdI"
              castShadow
              geometry={nodes.JoRHkRchuIHZFdI.geometry}
              material={materials.mEMAJQfiigHeUXV}
            />
            <mesh
              name="qJLFXXZhlqhKvcM"
              castShadow
              geometry={nodes.qJLFXXZhlqhKvcM.geometry}
              material={materials.mEMAJQfiigHeUXV}
            />
            <mesh
              name="thJvyyEdPZIkQGr"
              castShadow
              geometry={nodes.thJvyyEdPZIkQGr.geometry}
              material={materials.OFvWomWIIUgmKKA}
            />
            <mesh
              name="juMIjHdkYweLlGP"
              castShadow
              geometry={nodes.juMIjHdkYweLlGP.geometry}
              material={materials.NzmRSNqyvNKhkmK}
            />
            <mesh
              name="zNYAavJLMZZchIX"
              castShadow
              geometry={nodes.zNYAavJLMZZchIX.geometry}
              material={materials.ASadxrcBIAXFnLn}
            />
            <mesh
              name="bzbXKgxvWZbXAqu"
              castShadow
              geometry={nodes.bzbXKgxvWZbXAqu.geometry}
              material={materials.JKvAHnqjqlqshmY}
            />
            <mesh
              name="guzkNjLPdYYIFbm"
              castShadow
              geometry={nodes.guzkNjLPdYYIFbm.geometry}
              material={materials.oINmXIPcNKkHSJV}
            />
            <mesh
              name="CkZgGMshUOhytMM"
              castShadow
              geometry={nodes.CkZgGMshUOhytMM.geometry}
              material={materials.AvocVUvikCzzMtu}
            />
            <mesh
              name="oiLbjgjnUUhPosp"
              castShadow
              geometry={nodes.oiLbjgjnUUhPosp.geometry}
              material={materials.AvocVUvikCzzMtu}
            />
            <mesh
              name="nDWhlgWONddUcnN"
              castShadow
              geometry={nodes.nDWhlgWONddUcnN.geometry}
              material={materials.tyKqaDjBmuwfmrZ}
            />
            <mesh
              name="VAcTKRVsYcEMWxB"
              castShadow
              geometry={nodes.VAcTKRVsYcEMWxB.geometry}
              material={materials.dkOmcmuFedorUKC}
            />
          </group>
        </group>
      </group>
    </>
  )
}

useGLTF.preload('/laptop.glb')
